sudo: required
services:
    - docker

before_install:
     - docker build -f Dockerfile.dev -t raunakjodhawat/chucknorris:latest .

script:
    - docker run -e CI=true raunakjodhawat/chucknorris npm run test -- --coverage

deploy:
    edge: true
    provide: elasticbeanstalk
    region: "us-east-2"
    app: "ChuckNorrisClient"
    env: "Chucknorrisclient-env"
    bucket_name: "chuck-norris-elastic-bean"
    bucket_path: "chucktravis"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_CODE
    secret_access_key: "$AWS_SECRET_CODE"