sudo: required
services:
    - docker

before_install:
     - docker build -f Dockerfile.dev -t raunakjodhawat/chucknorris:latest .

script:
    - export REACT_APP_EXTERNAL_API_URL=$REACT_APP_EXTERNAL_API_URL
    - export REACT_APP_GATEWAY_API_URL=$REACT_APP_GATEWAY_API_URL
    - docker run -e CI=true -p -e REACT_APP_EXTERNAL_API_URL=$REACT_APP_EXTERNAL_API_URL -e REACT_APP_GATEWAY_API_URL=$REACT_APP_GATEWAY_API_URL "3000:3000" raunakjodhawat/chucknorris npm run test -- --coverage

after_success:
    - npm prune --production

deploy:
    edge: true
    provide: elasticbeanstalk
    region: "us-east-2"
    app: "ChuckNorrisClient"
    env: "Chucknorrisclient-env"
    bucket_name: "chuck-norris-elastic-bean"
    bucket_path: "chucktravis"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_CODE
    secret_access_key: "$AWS_SECRET_CODE"