FROM node:alpine

WORKDIR /chuck-norris-client
COPY ./package.json .
RUN npm i fsevents@latest -f --save-optional
RUN npm install
COPY . .
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent
CMD ["npm", "run", "start"]